# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GAN_test_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import GAN_test_config as config


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1038, 673)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 461, 631))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_vectorAdj = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_vectorAdj.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_vectorAdj.setObjectName("verticalLayout_vectorAdj")
        self.scrollArea_vectorAdj = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        self.scrollArea_vectorAdj.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrollArea_vectorAdj.setWidgetResizable(True)
        self.scrollArea_vectorAdj.setObjectName("scrollArea_vectorAdj")
        self.scrollAreaQGroupBox_vectorAdj = QtWidgets.QGroupBox()
        self.scrollAreaQGroupBox_vectorAdj.setGeometry(QtCore.QRect(0, 0, 457, 627))
        self.scrollAreaQGroupBox_vectorAdj.setObjectName("scrollAreaWidget_vectorAdj")

        self.scrollAreaQFormLayout_vectorAdj = QtWidgets.QFormLayout()

        self.horizontalSliders = []
        for i in range(config.numRandomLatent):
            newHorizontalSlider = QtWidgets.QSlider()
            newHorizontalSlider.setMinimum(-1000)
            newHorizontalSlider.setMaximum(1000)
            newHorizontalSlider.setSingleStep(50)
            newHorizontalSlider.setTracking(True)
            newHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
            newHorizontalSlider.setInvertedAppearance(False)
            newHorizontalSlider.setObjectName(f"horizontalSlider_vecSlider_{i}")
            
            newHorizontalSliderLabel = QtWidgets.QLabel()
            newHorizontalSliderLabel.setObjectName(f"horizontalSlider_vecLabel_{i}")
            newHorizontalSliderLabel.setText(f"{0.0:7.2f}")

            self.scrollAreaQFormLayout_vectorAdj.addRow(newHorizontalSliderLabel, newHorizontalSlider)
            self.horizontalSliders.append((newHorizontalSlider, newHorizontalSliderLabel))

        self.scrollAreaQGroupBox_vectorAdj.setLayout(self.scrollAreaQFormLayout_vectorAdj)
        self.scrollArea_vectorAdj.setWidget(self.scrollAreaQGroupBox_vectorAdj)
        self.verticalLayout_vectorAdj.addWidget(self.scrollArea_vectorAdj)

        # 
        self.label_generateWhileChange = QtWidgets.QLabel(self.centralwidget)
        self.label_generateWhileChange.setGeometry(QtCore.QRect(680, 20, 62, 52))
        self.label_generateWhileChange.setObjectName("label_generateWhileChange")
        self.label_generateWhileChange.setStyleSheet("font: 16px 'Arial';")
        
        self.checkBox_generateWhileChange = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_generateWhileChange.setGeometry(QtCore.QRect(700, 10, 21, 21))
        self.checkBox_generateWhileChange.setObjectName("checkBox_generateWhileChange")

        # result show
        self.label_resultImg = QtWidgets.QLabel(self.centralwidget)
        self.label_resultImg.setGeometry(QtCore.QRect(470, 70, 551, 551))
        self.label_resultImg.setObjectName("graphicsView_resultImg")
        self.label_resultImg.setStyleSheet("font: bold 24px ;background-color: #444444;")

        # random input
        self.pushButton_random = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_random.setGeometry(QtCore.QRect(470, 10, 71, 51))
        self.pushButton_random.setCheckable(False)
        self.pushButton_random.setAutoDefault(False)
        self.pushButton_random.setDefault(False)
        self.pushButton_random.setFlat(False)
        self.pushButton_random.setObjectName("pushButton_random")
        self.spinBox_mean = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spinBox_mean.setGeometry(QtCore.QRect(600, 10, 62, 22))
        self.spinBox_mean.setObjectName("spinBox_mean")
        self.spinBox_mean.setSingleStep(0.5)
        self.spinBox_mean.setValue(0.0)
        self.spinBox_std = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spinBox_std.setGeometry(QtCore.QRect(600, 40, 62, 22))
        self.spinBox_std.setObjectName("spinBox_std")
        self.spinBox_mean.setSingleStep(0.5)
        self.spinBox_std.setValue(1.0)

        self.label_mean = QtWidgets.QLabel(self.centralwidget)
        self.label_mean.setGeometry(QtCore.QRect(550, 10, 47, 14))
        self.label_mean.setStyleSheet("font: 18px 'Arial';")
        self.label_mean.setObjectName("label_mean")
        self.label_std = QtWidgets.QLabel(self.centralwidget)
        self.label_std.setGeometry(QtCore.QRect(550, 40, 47, 14))
        self.label_std.setStyleSheet("font: 18px 'Arial';")
        self.label_std.setObjectName("label_std")

        #
        self.pushButton_Generate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Generate.setGeometry(QtCore.QRect(770, 10, 71, 51))
        self.pushButton_Generate.setCheckable(False)
        self.pushButton_Generate.setAutoDefault(False)
        self.pushButton_Generate.setDefault(False)
        self.pushButton_Generate.setFlat(False)
        self.pushButton_Generate.setObjectName("pushButton_generate")

        # save button
        self.pushButton_saveVector = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_saveVector.setGeometry(QtCore.QRect(870, 10, 71, 26))
        self.pushButton_saveVector.setCheckable(False)
        self.pushButton_saveVector.setAutoDefault(False)
        self.pushButton_saveVector.setDefault(False)
        self.pushButton_saveVector.setFlat(False)
        self.pushButton_saveVector.setObjectName("pushButton_saveVec")

        self.pushButton_saveImage = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_saveImage.setGeometry(QtCore.QRect(870, 35, 71, 26))
        self.pushButton_saveImage.setCheckable(False)
        self.pushButton_saveImage.setAutoDefault(False)
        self.pushButton_saveImage.setDefault(False)
        self.pushButton_saveImage.setFlat(False)
        self.pushButton_saveImage.setObjectName("pushButton_saveImg")

        self.pushButton_saveAll = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_saveAll.setGeometry(QtCore.QRect(940, 10, 51, 51))
        self.pushButton_saveAll.setCheckable(False)
        self.pushButton_saveAll.setAutoDefault(False)
        self.pushButton_saveAll.setDefault(False)
        self.pushButton_saveAll.setFlat(False)
        self.pushButton_saveAll.setObjectName("pushButton_saveAll")

        # main window
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1038, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GAN Test"))
        self.pushButton_random.setText(_translate("MainWindow", "Rand"))
        self.pushButton_Generate.setText(_translate("MainWindow", "Generate\nImage"))
        self.pushButton_saveVector.setText(_translate("MainWindow", "Save Vector"))
        self.pushButton_saveImage.setText(_translate("MainWindow", "Save Image"))
        self.pushButton_saveAll.setText(_translate("MainWindow", "Save\nAll"))
        self.label_mean.setText(_translate("MainWindow", "Mean:"))
        self.label_std.setText(_translate("MainWindow", "std:"))
        self.label_generateWhileChange.setText(_translate("MainWindow", "realtime\npreview"))
